name: Keep Gigalixir App Alive

on:
  schedule:
    - cron: "*/3 * * * *"
  workflow_dispatch:  # Allow manual trigger

jobs:
  scale:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 使用方法：
        # - 在仓库 Variables 设置 `ACCOUNTS` 为 JSON 数组（每个元素是一个 Secret 名），例如：["ACCOUNT_1","ACCOUNT_2"]
        # - 为数组中的每个名称创建同名 Secret，内容为：
        #   第1行：域名；第2行：APP 名称；第3行及以后：.netrc（login/password）
        ACCOUNT_SECRET: ${{ fromJSON(vars.ACCOUNTS) }}
    steps:
      - name: Parse account secret
        shell: bash
        run: |
          printf '%s' "${{ secrets[matrix.ACCOUNT_SECRET] }}" > account.txt
          DOMAIN=$(head -n 1 account.txt | tr -d '\r')
          APP_NAME=$(sed -n '2p' account.txt | tr -d '\r')
          tail -n +3 account.txt > ~/.netrc
          chmod 600 ~/.netrc
          echo "DOMAIN=$DOMAIN" >> "$GITHUB_ENV"
          echo "APP_NAME=$APP_NAME" >> "$GITHUB_ENV"

      - name: Check domain health
        id: health_check
        run: |
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$DOMAIN" || echo "000")
          echo "status=$HTTP_STATUS" >> "$GITHUB_OUTPUT"
          echo "Domain $DOMAIN returned status: $HTTP_STATUS"
          if [ "$HTTP_STATUS" = "200" ]; then
            echo "Domain is healthy (200), skipping scale operation"
          else
            echo "Domain returned $HTTP_STATUS, proceeding with scale operation"
          fi

      - name: Install Gigalixir CLI
        if: steps.health_check.outputs.status != '200'
        run: |
          pip install gigalixir

      - name: Scale app
        if: steps.health_check.outputs.status != '200'
        run: |
          gigalixir ps:scale -a "${{ env.APP_NAME }}" -r 1
